### ISSUE TITLE
"There must be 2, 3 or 4 components in the version string"

### ISSUE THREAD

**Issue by leopic** [DaveVoyles/XamarinWebAPI#1]
I just downloaded the app and couldn't even get it to open on Xamarin when I ran into this issue, the problem seems to be all references to `__MvcPagesVersion__` in `XamarinWebAPI/XamarinWebAPI.csproj`.

Once I updated all of those, I was able to build. Reference https://forums.xamarin.com/discussion/15949/there-must-be-2-3-or-4-components-in-the-version-string

**Comment by DaveVoyles** [comment]
Thank you for pointing this out! 

I'm going to add a note to the README about this for clarification

**Comment by leopic** [comment]
@DaveVoyles I changed ```Version=__MvcPagesVersion__``` to something like ```Version=1.0.0```

**Comment by DaveVoyles** [comment]
Perfect, I'll make that change now. Thanks again for your help!

**Comment by leopic** [comment]
you bet, thank you!

**Comment by DaveVoyles** [comment]
How / where do you make this change? I'm opening up the project, but I cna't seem to find the string "Version=__MvcPagesVersion__"

**Comment by leopic** [comment]
I opened that file using VIM, not Xamarin, it's just an XML file in the end
:p

**Comment by DaveVoyles** [comment]
Thank you again, you saved me here!

I found it, made the changes, and just did a push.
